"""add balance to accounts

Revision ID: a054c0e39f57
Revises: 97935df032f9
Create Date: 2026-09-01 14:57:12.816719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a054c0e39f57'
down_revision: Union[str, Sequence[str], None] = '97935df032f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'balance')
    # ### end Alembic commands ###
